import type { Metadata } from "next";
import { Livvic } from "next/font/google";
import "./globals.css";

const livvicfont = Livvic({
	weight: ["100", "200","300", "400", "600","700"],
	subsets: ["vietnamese"],
});


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${livvicfont.className} antialiased`}>{children}</body>
		</html>
	);
}
